version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'webserver'
    restart: 'always'
    depends_on:
      - database
    ports:
      - "80:80"
      - "443:443"
    links: 
      - database
    environment:
      DB_ADRESS: database
      DB_USER: root
      DB_PASSWORD: root_password
      DB_TARGET: test_database
    volumes: 
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
  database:
    build:
      context: ./bin/database
    container_name: 'database'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    links:
      - database
    ports:
      - '8080:80'
